name: Codespell
on: [pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: codespell
        uses: codespell-project/actions-codespell@v2
        with:
          # only show the typo detected but don't make workflow to fail
          only_warn: 1
          skip: "*.ts"
          # word to exclude must be always lowercase as must be same of the codespell dictionary
          ignore_words_list: ba